
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-conf

data:
  SPRING_PROFILES_ACTIVE: "production"
  DB_USER: "postgres"
  DB_PASSWORD: "{{ .Values.postgress_pass }}"
  DB_JDBC_URL: "jdbc:postgresql://{{ .Release.Name }}-postgres-svc:5432/postzegel-reporter"
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Release.Name }}-kafka-svc:9092"
  KAFKA_CLIENT_ID: "stamp-reporter"
  STAMP_SERVER_URL: "http://postzegel-backend-service.postzegel-backend.svc.cluster.local:8080"

