
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-svc
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: http
    protocol: TCP
    name: http
  selector:
    kind: {{ .Release.Name }}-kafka
